services:
  web:
    build: .
    container_name: movielibrary_web
    env_file: .env
    command: uvicorn movielibrary.main:app --host 0.0.0.0 --port 8000

    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: films_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  bot:
    build:
      context: ./telegrambot
    container_name: movielibrary_bot
    env_file: .env
    restart: always

volumes:
  postgres_data:
