services:
  web:
    build: .
    container_name: movielibrary_web
    command: uvicorn movielibrary.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:16
    container_name: films_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
