services:
  web:
    build: .
    container_name: movielibrary_web
    env_file: .env
    command: uvicorn movielibrary.app:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    mem_limit: 150m
    mem_reservation: 100m

  db:
    image: postgres:16
    container_name: films_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    mem_limit: 100m
    mem_reservation: 50m

  bot:
    build:
      context: ./telegrambot
    container_name: movielibrary_bot
    env_file: .env
    restart: always
    mem_limit: 50m
    mem_reservation: 30m
volumes:
  postgres_data:
