"""add type column to films

Revision ID: ae1073922c14
Revises: 346061ba5154
Create Date: 2025-08-22 12:56:33.553740

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae1073922c14"
down_revision: Union[str, Sequence[str], None] = "346061ba5154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    mediatype_enum = sa.Enum("movie", "series", name="mediatype")
    mediatype_enum.create(op.get_bind(), checkfirst=True)

    op.drop_constraint("film_country_film_id_fkey", "film_country", type_="foreignkey")
    op.create_foreign_key(
        "film_country_film_id_fkey", "film_country", "films", ["film_id"], ["id"]
    )
    op.drop_constraint("film_genre_film_id_fkey", "film_genre", type_="foreignkey")
    op.create_foreign_key(
        "film_genre_film_id_fkey", "film_genre", "films", ["film_id"], ["id"]
    )

    op.add_column(
        "films",
        sa.Column("type", mediatype_enum, nullable=True),
    )

    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE films
            SET type = CASE
                WHEN title ILIKE '%сериал%' THEN 'series'::mediatype
                ELSE 'movie'::mediatype
            END
            WHERE type IS NULL
        """)
    )

    op.alter_column("films", "type", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("films", "type")
    op.drop_constraint(None, "film_genre", type_="foreignkey")
    op.create_foreign_key(
        op.f("film_genre_film_id_fkey"),
        "film_genre",
        "films",
        ["film_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "film_country", type_="foreignkey")
    op.create_foreign_key(
        op.f("film_country_film_id_fkey"),
        "film_country",
        "films",
        ["film_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
